
[functions.crear-preferencia-pago]
enabled = true
verify_jwt = true
import_map = "./functions/crear-preferencia-pago/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crear-preferencia-pago/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crear-preferencia-pago/*.html" ]

[functions.enviar-notificacion-pedido]
enabled = true
verify_jwt = true
import_map = "./functions/enviar-notificacion-pedido/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/enviar-notificacion-pedido/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/enviar-notificacion-pedido/*.html" ]

[functions.sitemap]
enabled = true
verify_jwt = true
import_map = "./functions/sitemap/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sitemap/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sitemap/*.html" ]
